# Generated by Django 3.2.3 on 2021-07-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=16)),
                ('message', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
