# Generated by Django 5.0.1 on 2024-02-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_contact', '0002_auto_20210718_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='persian_enquiry',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='persian_fullname',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='persian_subject',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
