# Generated by Django 3.2.3 on 2021-11-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('family', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('CEO', 'CEO')], max_length=15)),
                ('linkedin', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team members',
                'ordering': ['position'],
            },
        ),
    ]
