# Generated by Django 5.0.1 on 2024-02-12 20:06

import peravia_team.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('family', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('Co-Founder & CEO', 'Co-Founder & CEO'), ('International Procurement Manager', 'International Procurement Manager'), ('Procurement Manager', 'Procurement Manager'), ('Administrative Manager', 'Administrative Manager'), ('Financial Manager', 'Financial Manager'), ('Industrial Accountant', 'Industrial Accountant'), ('IT Manager', 'IT Manager'), ('Brand Manager', 'Brand Manager')], max_length=200)),
                ('rank', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=0)),
                ('member_image', models.ImageField(blank=True, null=True, upload_to=peravia_team.models.upload_image_path)),
                ('linkedin', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team members',
                'ordering': ['rank'],
            },
        ),
    ]
