# Generated by Django 3.2.3 on 2021-11-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(choices=[('Co-Founder and CEO', 'Co-Founder and CEO'), ('Export and International Procurement Manager', 'Export and International Procurement Manager'), ('Procurement Manager', 'Procurement Manager'), ('Administrative Manager', 'Administrative Manager'), ('Financial Manager', 'Financial Manager'), ('Industrial Accountant', 'Industrial Accountant'), ('IT Manager', 'IT Manager'), ('Brand Manager', 'Brand Manager')], max_length=200),
        ),
    ]
