# Generated by Django 3.2.3 on 2021-11-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_team', '0002_alter_team_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(choices=[('Co-Founder & CEO', 'Co-Founder & CEO'), ('Export and International Procurement Manager', 'Export and International Procurement Manager'), ('Procurement Manager', 'Procurement Manager'), ('Administrative Manager', 'Administrative Manager'), ('Financial Manager', 'Financial Manager'), ('Industrial Accountant', 'Industrial Accountant'), ('IT Manager', 'IT Manager'), ('Brand Manager', 'Brand Manager')], max_length=200),
        ),
    ]
