# Generated by Django 3.2.3 on 2021-11-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_team', '0004_alter_team_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='position_abbreviation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
