# Generated by Django 3.2.3 on 2021-11-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_team', '0005_team_position_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='position_abbreviation',
        ),
    ]
