# Generated by Django 3.2.3 on 2021-11-07 16:35

from django.db import migrations, models
import peravia_team.models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_team', '0006_remove_team_position_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=peravia_team.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(choices=[('Co-Founder & CEO', 'Co-Founder & CEO'), ('International Procurement Manager', 'International Procurement Manager'), ('Procurement Manager', 'Procurement Manager'), ('Administrative Manager', 'Administrative Manager'), ('Financial Manager', 'Financial Manager'), ('Industrial Accountant', 'Industrial Accountant'), ('IT Manager', 'IT Manager'), ('Brand Manager', 'Brand Manager')], max_length=200),
        ),
    ]
