# Generated by Django 3.2.3 on 2021-11-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_team', '0007_auto_20211107_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=0),
        ),
    ]
