# Generated by Django 3.2.3 on 2021-11-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_team', '0008_team_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['rank'], 'verbose_name': 'Team', 'verbose_name_plural': 'Team members'},
        ),
    ]
