# Generated by Django 3.2.3 on 2021-11-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_team', '0009_alter_team_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='image',
            new_name='member_image',
        ),
    ]
