# Generated by Django 5.0.1 on 2024-02-12 20:06

import django.db.models.deletion
import peravia_setting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=peravia_setting.models.upload_certificate_image_path)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=peravia_setting.models.upload_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('site_address', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to=peravia_setting.models.upload_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('short_description', models.TextField(default='Short Description')),
                ('phone', models.CharField(max_length=25)),
                ('fax', models.CharField(max_length=25)),
                ('support_email', models.EmailField(max_length=254, verbose_name='email address')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Social Media', max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peravia_setting.sitesetting')),
            ],
        ),
    ]
