# Generated by Django 3.2.3 on 2021-07-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(),
        ),
    ]
