# Generated by Django 3.2.3 on 2021-07-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_setting', '0002_alter_sitesetting_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='short_description',
            field=models.TextField(default='Short Description'),
        ),
    ]
