# Generated by Django 3.2.3 on 2021-07-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_setting', '0003_sitesetting_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(default='Social Media', max_length=20),
        ),
    ]
