# Generated by Django 3.2.3 on 2021-07-24 21:59

from django.db import migrations, models
import peravia_setting.models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_setting', '0004_auto_20210722_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('site_address', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to=peravia_setting.models.upload_image_path)),
            ],
        ),
    ]
