# Generated by Django 3.2.3 on 2022-05-26 06:38

from django.db import migrations, models
import peravia_setting.models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_setting', '0005_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=peravia_setting.models.upload_certificate_image_path)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=peravia_setting.models.upload_file_path)),
            ],
        ),
    ]
