# Generated by Django 3.2.3 on 2021-06-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_accounts', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
