# Generated by Django 5.0.1 on 2024-02-12 20:06

import ckeditor_uploader.fields
import django.db.models.deletion
import peravia_blog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('persian_title', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('draft', models.BooleanField(default=False)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to=peravia_blog.models.upload_image_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('persian_title', models.CharField(blank=True, default='', max_length=250, null=True, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('summary', models.CharField(max_length=500)),
                ('persian_summary', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('news_image', models.ImageField(blank=True, null=True, upload_to=peravia_blog.models.upload_image_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-created_on'],
            },
        ),
    ]
