# Generated by Django 5.0.1 on 2024-03-03 23:06

import ckeditor_uploader.fields
import peravia_blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=peravia_blog.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=peravia_blog.models.upload_image_path),
        ),
    ]
