# Generated by Django 3.2.3 on 2021-11-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
