# Generated by Django 3.2.3 on 2021-11-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_blog', '0002_blogpost_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='image',
            new_name='post_image',
        ),
    ]
