# Generated by Django 3.2.3 on 2022-04-16 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_blog', '0010_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
    ]
