# Generated by Django 3.2.3 on 2022-04-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_blog', '0014_auto_20220419_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
