# Generated by Django 5.0.1 on 2024-02-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_blog', '0015_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='persian_title',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='persian_summary',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='persian_title',
            field=models.CharField(blank=True, default='', max_length=250, null=True, unique=True),
        ),
    ]
