# Generated by Django 3.2.3 on 2021-07-06 12:21

from django.db import migrations, models
import django.db.models.deletion
import peravia_products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to=peravia_products.models.upload_image_path)),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('application', models.CharField(default='', max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('main_application', models.TextField()),
                ('caution', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=peravia_products.models.upload_image_path)),
                ('characteristics', models.FileField(blank=True, null=True, upload_to=peravia_products.models.upload_file_path)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peravia_products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peravia_products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('products', models.ManyToManyField(to='peravia_products.Product')),
            ],
        ),
    ]
