# Generated by Django 5.0.1 on 2024-02-12 20:06

import django.db.models.deletion
import peravia_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('persian_title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(max_length=300)),
                ('persian_description', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Main Category',
                'verbose_name_plural': 'Main Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('persian_title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=peravia_products.models.upload_category_image_path)),
                ('main_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peravia_products.maincategory')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('persian_title', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('slug', models.SlugField(max_length=150)),
                ('application', models.CharField(default='', max_length=250)),
                ('persian_application', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('persian_description', models.TextField(blank=True, default='', null=True)),
                ('main_application', models.TextField()),
                ('persian_main_application', models.TextField(blank=True, default='', null=True)),
                ('caution', models.TextField()),
                ('persian_caution', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=peravia_products.models.upload_image_path)),
                ('characteristics', models.FileField(blank=True, null=True, upload_to=peravia_products.models.upload_file_path)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peravia_products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('persian_title', models.TextField(blank=True, default='', null=True)),
                ('product', models.ManyToManyField(to='peravia_products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('persian_title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peravia_products.product')),
            ],
        ),
    ]
