# Generated by Django 3.2.3 on 2021-07-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
