# Generated by Django 3.2.3 on 2021-07-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_products', '0002_auto_20210706_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
