# Generated by Django 5.0.1 on 2024-02-22 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_products', '0002_alter_advantage_persian_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantage',
            name='product',
        ),
        migrations.CreateModel(
            name='AdvantageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peravia_products.advantage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peravia_products.product')),
            ],
        ),
        migrations.AddField(
            model_name='advantage',
            name='products',
            field=models.ManyToManyField(through='peravia_products.AdvantageProduct', to='peravia_products.product'),
        ),
    ]
