# Generated by Django 3.2.3 on 2022-05-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_products', '0004_alter_advantage_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='products',
            field=models.ManyToManyField(to='peravia_products.Product'),
        ),
    ]
