# Generated by Django 3.2.3 on 2022-05-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_products', '0005_alter_advantage_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
