# Generated by Django 3.2.3 on 2022-05-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_products', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
