# Generated by Django 3.2.3 on 2022-05-24 12:45

from django.db import migrations, models
import django.db.models.deletion
import peravia_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_products', '0008_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Main Category',
                'verbose_name_plural': 'Main Categories',
                'ordering': ['title'],
            },
        ),
        migrations.RenameField(
            model_name='advantage',
            old_name='products',
            new_name='product',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=peravia_products.models.upload_category_image_path),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peravia_products.maincategory'),
        ),
    ]
