# Generated by Django 3.2.3 on 2022-05-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_products', '0010_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
