# Generated by Django 5.0.1 on 2024-02-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_products', '0011_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='persian_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='persian_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='persian_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='persian_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='persian_description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='persian_title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='specification',
            name='persian_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
