# Generated by Django 5.0.1 on 2024-02-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_products', '0012_advantage_persian_title_category_persian_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='persian_title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
