# Generated by Django 5.0.1 on 2024-02-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peravia_products', '0014_alter_advantage_persian_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='persian_application',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='persian_caution',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='persian_main_application',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
